version: 0.8
node_id: lambda-searcher
metastore_uri: ${QW_LAMBDA_METASTORE_CONNECTION_STRING}
default_index_root_uri: s3://${QW_LAMBDA_INDEX_BUCKET}/${QW_LAMBDA_INDEX_PREFIX:-index}
data_dir: /tmp
searcher:
  partial_request_cache_capacity: ${QW_LAMBDA_PARTIAL_REQUEST_CACHE_CAPACITY:-64M}
  request_timeout_secs: 600